### ISSUE TITLE
Latest release points to 1.1.0

### ISSUE THREAD

**Issue by jehrhardt** [boxen/puppet-emacs#10]
On  Github's release page, 1.1.0 is marked as the latest release. The two newer releases are hidden on the page. A user would probably install the outdated version 1.1.0.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
