### ISSUE TITLE
Fatal error 4: Illegal instruction when installing emacs via puppet-emacs

### ISSUE THREAD

**Issue by goxberry** [boxen/puppet-emacs#5]
If I run boxen and include emacs, the installation process works, but in running emacs, I get an error:

```
Geoffs-MacBook-Pro:repo goxberry$ emacs
Fatal error 4: Illegal instruction
```

If I manually uninstall emacs and reinstall it, it seems to work.

```
Geoffs-MacBook-Pro:repo goxberry$ brew uninstall emacs
Uninstalling /opt/boxen/homebrew/Cellar/emacs/24.3-boxen1...
Geoffs-MacBook-Pro:repo goxberry$ brew install emacs
==> Downloading http://ftpmirror.gnu.org/emacs/emacs-24.3.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/opt/boxen/homebrew/Cellar/emacs/24.3 --without-dbus -
==> make
==> make install
==> Summary
/opt/boxen/homebrew/Cellar/emacs/24.3: 3843 files, 96M, built in 4.1 minutes
Geoffs-MacBook-Pro:repo goxberry$ emacs --version
GNU Emacs 24.3.1
Copyright (C) 2013 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

I suspect this error is related to https://github.com/boxen/puppet-tmux/issues/1, https://github.com/boxen/puppet-homebrew/issues/12, and https://github.com/boxen/puppet-homebrew/issues/17.

**Comment by jacobbednarz** [comment]
This module has been deprecated in favour of using the [in built Homebrew/Caskroom](https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17) support. Please give that a try and let me know if you're still having issues.
